apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-backend
  namespace: default
  labels:
    app: kubeflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeflow-backend
  template:
    metadata:
      labels:
        app: kubeflow-backend
    spec:
      containers:
      - name: backend
        image: kubeflow-backend:latest
        imagePullPolicy: Never  # Use local image built with kind
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_HOST
          value: "ollama-service"
        - name: OLLAMA_PORT
          value: "11434"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kubeflow-backend-service
  namespace: default
spec:
  selector:
    app: kubeflow-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080
  type: NodePort  # Exposed for external access